import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import { Button } from "@mui/material";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const Navbar = () => {
  return (
    <>
      <Link href={"/pie"}>
        <Button>Pie charts</Button>
      </Link>{" "}
      <Link href={"/bar"}>
        <Button color="secondary">Bar charts</Button>
      </Link>
    </>
  );
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
